name: prueba_evertec
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.0.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  go_router: ^13.2.2
  intl: ^0.19.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
